/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCompetitionIdRouteImport } from './routes/admin/$competitionId'
import { Route as ClimbTokenRouteImport } from './routes/climb.$token'
import { Route as ScoreboardCompetitionIdRouteImport } from './routes/scoreboard.$competitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionIdRoute = AdminCompetitionIdRouteImport.update({
  id: '/admin/$competitionId',
  path: '/admin/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimbTokenRoute = ClimbTokenRouteImport.update({
  id: '/climb/$token',
  path: '/climb/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardCompetitionIdRoute = ScoreboardCompetitionIdRouteImport.update({
  id: '/scoreboard/$competitionId',
  path: '/scoreboard/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$competitionId': typeof AdminCompetitionIdRoute
  '/climb/$token': typeof ClimbTokenRoute
  '/scoreboard/$competitionId': typeof ScoreboardCompetitionIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$competitionId': typeof AdminCompetitionIdRoute
  '/climb/$token': typeof ClimbTokenRoute
  '/scoreboard/$competitionId': typeof ScoreboardCompetitionIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$competitionId': typeof AdminCompetitionIdRoute
  '/climb/$token': typeof ClimbTokenRoute
  '/scoreboard/$competitionId': typeof ScoreboardCompetitionIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/$competitionId'
    | '/climb/$token'
    | '/scoreboard/$competitionId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/$competitionId'
    | '/climb/$token'
    | '/scoreboard/$competitionId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/$competitionId'
    | '/climb/$token'
    | '/scoreboard/$competitionId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminCompetitionIdRoute: typeof AdminCompetitionIdRoute
  ClimbTokenRoute: typeof ClimbTokenRoute
  ScoreboardCompetitionIdRoute: typeof ScoreboardCompetitionIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$competitionId': {
      id: '/admin/$competitionId'
      path: '/admin/$competitionId'
      fullPath: '/admin/$competitionId'
      preLoaderRoute: typeof AdminCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climb/$token': {
      id: '/climb/$token'
      path: '/climb/$token'
      fullPath: '/climb/$token'
      preLoaderRoute: typeof ClimbTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard/$competitionId': {
      id: '/scoreboard/$competitionId'
      path: '/scoreboard/$competitionId'
      fullPath: '/scoreboard/$competitionId'
      preLoaderRoute: typeof ScoreboardCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminCompetitionIdRoute: AdminCompetitionIdRoute,
  ClimbTokenRoute: ClimbTokenRoute,
  ScoreboardCompetitionIdRoute: ScoreboardCompetitionIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
